import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

// Replace these two values before the public launch. The email fallback keeps the static site usable.
const siteConfig = { bookingUrl: '', contactEmail: 'hello@wakiilai.com' };

const en = {
  nav: { solutions: 'Solutions', method: 'How we work', proof: 'Proof', security: 'Security', about: 'About', demo: 'View demo', cta: 'Book a discovery call' },
  common: { contact: 'Book a discovery call', explore: 'Explore solutions', openDemo: 'Open the live demo', readProof: 'See the proof', internal: 'Verified internal evidence', controlled: 'Controlled dry-run', capability: 'Current capability', planned: 'Planned capability', customerResult: 'Customer result', claimSuffix: 'requires evidence', footerTagline: 'AI systems for serious operations.', footerClaims: 'Claims classified before publication' },
  home: {
    eyebrow: 'AI systems for serious operations', title: 'Make the work move with more control.', intro: 'Wakiil designs and operates AI-powered automation systems that help businesses work faster, safer, and with more control.', note: 'From the first signal to the final audit trail, every consequential step has an owner.',
    capabilitiesTitle: 'Automation that carries the whole operation.', capabilitiesBody: 'Start with one process. Build a reliable layer around it. Expand when the evidence is strong.',
    capabilities: [
      ['Consultancy', 'Find the work worth automating.', 'We map the operation before we choose the tool, model, or integration.'],
      ['AI automation', 'Turn repeated decisions into safe systems.', 'Events, procedures, AI drafts, approvals, and actions work as one operating path.'],
      ['Digital operations assistants', 'Give the team capacity without losing control.', 'Bounded assistants handle repeatable work while people keep authority over consequential decisions.'],
    ],
    proofTitle: 'Built for the moments where “almost right” is not enough.', proofBody: 'Our logistics proof shows how a failed delivery becomes a traceable, reviewable customer operation.', proofFacts: ['Six documented workflow modules across the operating story', 'Human approval before consequential action', 'Dry-run provider-result handling and audit recording'],
    methodTitle: 'A measured path from idea to operation.', methodBody: 'The first engagement is a controlled pilot, not a leap of faith.', methodSteps: ['Discover', 'Map', 'Secure', 'Pilot', 'Launch', 'Improve'], bottomTitle: 'Your next automation should be easier to trust.', bottomBody: 'Bring us one process that is slowing the business down. We will help you decide what to automate, what to protect, and what to measure.',
  },
  solutions: {
    eyebrow: 'What Wakiil can design and implement', title: 'A practical AI layer for the work you already do.', intro: 'Wakiil combines process design, integrations, AI, and operational controls into systems people can safely use.',
    items: [
      ['01', 'AI automation consultancy', 'See the operation clearly before changing it.', 'We identify the process, owners, systems, exceptions, and outcomes that matter. Then we shape a roadmap that can be delivered in controlled stages.', ['Process discovery', 'Systems and data mapping', 'Automation roadmap', 'Pilot definition']],
      ['02', 'Custom integrations', 'Connect the systems your team already depends on.', 'We make business events, operational facts, approved procedures, and next actions travel across the right systems without losing ownership.', ['API and system mapping', 'Event-driven workflows', 'Data boundaries', 'Failure handling']],
      ['03', 'Workflow automation', 'Make the next best action easier to take.', 'We connect operational events to approved procedures, grounded AI outputs, human review, and traceable actions.', ['AI-assisted decisions', 'Human approval controls', 'Audit-friendly execution', 'Manual fallback paths']],
      ['04', 'Digital operations assistants', 'Give repeatable work a reliable assistant.', 'Wakiil can design bounded assistants for support, documents, finance, compliance, and operations. The current verified proof remains logistics.', ['Customer support', 'Document processing', 'Operational handoffs', 'Managed optimisation']],
    ],
    ctaTitle: 'Start with the process everyone already knows is painful.', ctaBody: 'A discovery call turns a broad AI ambition into a specific, measurable first move.',
  },
  method: {
    eyebrow: 'How we work', title: 'Build confidence in the same order you build the system.', intro: 'Every engagement moves from understanding to controlled action. The delivery method is part of the product.',
    steps: [['01', 'Discovery', 'Name the operational problem, the people involved, and the outcome that would make the work worthwhile.'], ['02', 'Operations mapping', 'Trace systems, data, decision points, exceptions, manual fallbacks, and the owners of each step.'], ['03', 'Security and access review', 'Define what the automation may read, what it may do, who may approve it, and where secrets must stay.'], ['04', 'Controlled pilot', 'Prove one bounded process with staging data, explicit failure handling, and a measurable baseline.'], ['05', 'Production launch', 'Move through a deliberate release with rollback paths, support ownership, and clear customer boundaries.'], ['06', 'Monitoring and support', 'Watch outcomes, provider results, errors, approvals, and unresolved work after launch.'], ['07', 'Expansion', 'Use the evidence from one operation to decide which adjacent process earns the next investment.']],
    notesTitle: 'What professional delivery includes', notes: ['A named owner for consequential actions', 'Staging before live data is touched', 'Failure notifications and manual fallback', 'A record of what happened and why', 'A support path after launch'],
  },
  proof: {
    eyebrow: 'Proof, clearly classified', title: 'One delivery exception, carried from signal to evidence.', intro: 'This is internal Wakiil and MK Deliver implementation evidence. It is not an external customer case study.', caseLabel: 'MKD-0066 / customer unavailable', caseTitle: 'The operation does not stop at an AI draft.', caseBody: 'A failed delivery enters the system as a durable event. The procedure guides the draft. A human approves the consequential action. The latest state is checked again before the result is recorded.', facts: [['06', 'documented workflow modules'], ['01', 'human approval boundary'], ['00', 'real customer messages in dry-run']], evidenceTitle: 'What the evidence shows', evidence: ['Durable event and outbox handling', 'Duplicate approval and stale revision protection', 'Procedure-grounded draft in English and Somali', 'Access controls and approval allowlists', 'Server-side credential handling in the implementation design', 'Defined negative-test scenarios', 'Dry-run provider-result handling and audit recording'], disclaimer: 'Evidence captured from the internal cloud dry-run. Production customer messaging remains disabled in this demonstration.'
  },
  security: {
    eyebrow: 'Security and trust', title: 'Automation should make responsibility clearer, not blur it.', intro: 'We design the control boundary before we design the clever part. Access, approval, data exposure, and failure handling are first-class product decisions.', controls: [['Human approval', 'Consequential customer actions pause for an authorised person instead of running on an unreviewed recommendation.'], ['Fresh-state checks', 'Approved actions re-read the latest operational state before they execute.'], ['Access controls', 'Public customer surfaces receive safe projections. Private operational data stays behind server-side access and approval allowlists.'], ['Durable audit trail', 'Events, approvals, attempts, provider results, and failures remain traceable for review.'], ['Failure handling', 'Duplicate work, stale approvals, uncertain provider results, and invalid input have explicit paths.'], ['Credential handling', 'Server-side credentials stay out of browser code and public exports.']], boundaryTitle: 'Demo is not production', boundaryBody: 'The public showcase explains the operating model. The underlying demonstration uses controlled data and a test recipient. A production rollout requires a separate access review, environment setup, and acceptance plan.', boundaryPoints: ['No customer data in the public demo', 'No production recipients in the current message adapter', 'No certification claim without independent confirmation']
  },
  about: { eyebrow: 'About Wakiil', title: 'A company for the work between intention and execution.', intro: 'Wakiil helps businesses turn operational knowledge into systems that can notice, decide, act, and explain what happened.', statement: 'The goal is not to add AI to a process. The goal is to make the process safer, clearer, and easier to improve.', pillars: [['Practical', 'Start with the work that creates friction today, not an abstract transformation programme.'], ['Controlled', 'Keep people in charge of consequential decisions and make the boundary visible.'], ['Expandable', 'Build a foundation that can grow from one workflow into a connected operating layer.']], fitTitle: 'Good fit', fitBody: 'Teams with repeatable work, scattered systems, visible exceptions, and a leader who wants measurable progress.', notFitTitle: 'Not a shortcut', notFitBody: 'Wakiil is not a promise of autonomous magic or a replacement for operational ownership.' },
  contact: { eyebrow: 'Start a conversation', title: 'Bring us one process worth making better.', intro: 'Tell us where work slows down, where decisions repeat, and where a clearer operating path would create value.', bookingTitle: 'Book a discovery call', bookingBody: 'We will use the first conversation to understand the process, the systems around it, and whether a controlled pilot makes sense.', bookingButton: 'Open calendar', emailLabel: 'Or email', questionsTitle: 'Useful starting questions', questions: ['What process creates the most avoidable coordination?', 'Where do staff lose context between systems?', 'Which action needs a human decision today?', 'What would a successful pilot prove?'], note: 'Pricing is based on operational scope, system complexity, risk, transaction volume, implementation effort, and ongoing support. Exact pricing follows discovery.' },
  demo: { eyebrow: 'Interactive operating story', title: 'From a failed delivery to a resolved customer.', intro: 'Play the story to see how one operational event moves through intake, decision, approval, action, and audit.', play: 'Play the full story', reset: 'Reset visual', ready: 'Ready to play', scenario: 'Live scenario / MKD-0066', scenarioBody: 'Delivery attempt unsuccessful / customer unavailable', flow: ['Event detected', 'Case created', 'AI draft', 'Human approval', 'Action audited'], captions: ['A delivery failure becomes a durable, traceable event instead of an informal message.', 'Wakiil opens a case with the shipment facts the employee needs to act.', 'The response is grounded in approved facts and the company procedure.', 'The consequential customer action pauses for an authorised human decision.', 'The latest state is checked, the action is recorded, and the case can resolve safely.'], manualTitle: 'Without automation', manualBody: 'People coordinate the incident across scattered channels.', controlledTitle: 'With Wakiil automation', controlledBody: 'One event becomes a controlled, reviewable support process.', manual: ['Driver reports a failed delivery', 'Support searches for the shipment', 'Someone decides what to tell the customer', 'Customer waits for a response', 'Records are incomplete'], controlled: ['Delivery event captured', 'Exception case created', 'AI prepares a grounded support draft', 'Human approval controls the action', 'Action and audit are recorded'], galleryTitle: 'Workflow modules. One operating story.', galleryBody: 'Each card connects a documented module to the business promise it supports.', miniFlow: ['Event', 'Verify', 'Case', 'Guide'], manualBadge: 'Manual', controlledBadge: 'Controlled', playWorkflow: 'Play workflow', playing: 'Playing', closingEyebrow: 'Wakiil AI Solutions', closingTitle: 'Not another chatbot. An operating layer for the work that matters.', cards: [['Event intake', 'Catch the problem before it disappears', 'A failed delivery becomes a durable, traceable exception.', 'Detect'], ['Customer intake', 'Turn a customer message into action', 'A request is verified, understood, and routed safely.', 'Support'], ['Customer support', 'Answer safely, escalate intelligently', 'Safe questions get answers. Consequential requests become handoffs.', 'Support'], ['Approval boundary', 'Keep humans in control', 'AI prepares the recommendation. An authorised person approves the action.', 'Govern'], ['Approved decision', 'Act only on the latest facts', 'The shipment is checked again and the provider result is recorded.', 'Execute'], ['Draft revision', 'Improve the response without losing control', 'A revised draft returns to the approval loop.', 'Refine'], ['Showcase canvas', 'Make the operating model visible', 'A pitch-ready view connects support, AI, control, action, and audit.', 'Explain']] }
};

const so = {
  nav: { solutions: 'Xalalka', method: 'Sida aan u shaqayno', proof: 'Caddeyn', security: 'Amni', about: 'Nagu saabsan', demo: 'Daawo demo', cta: 'Qabso kulan hordhac ah' },
  common: { contact: 'Qabso kulan hordhac ah', explore: 'Baadh xalalka', openDemo: 'Fur demo-ga', readProof: 'Eeg caddeynta', internal: 'Caddeyn gudaha ah oo la xaqiijiyay', controlled: 'Tijaabo la xakameeyay', capability: 'Awoodda hadda', planned: 'Awood la qorsheeyay', customerResult: 'Natiijada macaamiil', claimSuffix: 'caddeyn ayaa loo baahan yahay', footerTagline: 'Nidaamyo AI ah oo loogu talagalay hawlo dhab ah.', footerClaims: 'Sheegashooyinka waa la kala saaraa ka hor daabacaadda' },
  home: { ...en.home, eyebrow: 'Nidaamyo AI ah oo loogu talagalay hawlo dhab ah', title: 'Shaqada hore ugu wad xakameyn dheeraad ah.', intro: 'Wakiil waxa uu naqshadeeyaa oo maamulaa nidaamyo otomaatig ah oo AI ku shaqeeya, si ganacsigu u shaqeeyo si dhakhso ah, ammaan badan, oo la xakameyn karo.', note: 'Laga bilaabo calaamadda ugu horreysa ilaa diiwaanka ugu dambeeya, tallaabo kasta oo muhiim ah waxay leedahay masuul.', capabilitiesTitle: 'Automation qaadi karta hawsha oo dhan.', capabilitiesBody: 'Ku bilow hal hab. Ku dhis lakab la isku halayn karo. Balaadhi marka caddeyntu xoog yeelato.', capabilities: [['La-talin', 'Hel shaqada mudan in la otomaatig gareeyo.', 'Waxaan marka hore khariidaynaa hawsha ka hor inta aan la dooran qalab, model, ama isku xir.'], ['AI automation', 'Go’aamada soo noqnoqda u beddel nidaamyo ammaan ah.', 'Dhacdooyinka, habraacyada, qoraallada AI, oggolaanshaha, iyo ficilladu waxay noqdaan hal waddo.'], ['Kaaliyeyaal hawleed dijitaal ah', 'Kooxda sii awood adigoon lumin xakameynta.', 'Kaaliyeyaashu waxay qabtaan shaqo soo noqnoqota, dadkuna waxay hayaan go’aamada muhiimka ah.']], proofTitle: 'Waxaa loo dhisay daqiiqadaha “ku dhowaad sax” aysan ku filnayn.', proofBody: 'Caddeyntayada logistics-ku waxay muujinaysaa sida delivery fashilmay uu u noqdo hawl taageero oo la raadin karo lana qiimeyn karo.', proofFacts: ['Lix workflow module oo la diiwaangeliyay', 'Oggolaansho qof ka hor ficil muhiim ah', 'Natiijada provider-ka dry-run iyo audit'], methodTitle: 'Jid la cabbiri karo oo fikrad looga gudbo hawl dhab ah.', methodBody: 'Hawlgalka ugu horreeya waa tijaabo la xakameeyay, ma aha bood aan la hubin.', methodSteps: ['Baadh', 'Khariidee', 'Aamin', 'Tijaabi', 'Daahfur', 'Hagaaji'], bottomTitle: 'Automation-ka xiga waa inuu fududaado in la aamino.', bottomBody: 'Noo keen hal hab oo ganacsiga dib u dhigaya. Waxaan kaa caawinaynaa waxa la otomaatig gareeyo, waxa la ilaaliyo, iyo waxa la cabbiro.' },
  solutions: { ...en.solutions, eyebrow: 'Waxa Wakiil naqshadayn karo oo hirgelin karo', title: 'Lakab AI oo wax ku ool ah oo ku shaqeeya hawsha aad hore u qabato.', intro: 'Wakiil wuxuu isku daraa naqshadaynta hawsha, isku xirka nidaamyada, AI, iyo xakameyn hawleed.', items: [['01', 'La-talin AI automation', 'Hawsha si cad u arag ka hor intaadan beddelin.', 'Waxaan aqoonsannaa hawsha, masuuliyiinta, nidaamyada, xaaladaha gaarka ah, iyo natiijooyinka muhiimka ah. Kadib waxaan samaynaa qorshe lagu hirgelin karo marxalado la xakameeyay.', ['Baadhista hawsha', 'Khariidaynta nidaamyada iyo xogta', 'Qorshaha automation-ka', 'Qeexidda tijaabada']], ['02', 'Isku xirro gaar ah', 'Isku xir nidaamyada ay kooxdaadu ku tiirsan tahay.', 'Waxaan dhacdooyinka ganacsiga, xaqiiqooyinka hawlgalka, habraacyada la ansixiyay, iyo ficillada xiga gaarsiinnaa nidaamyada saxda ah iyadoo masuuliyaddu aysan lumin.', ['Khariidaynta API iyo nidaamyada', 'Workflow-yada ku shaqeeya dhacdooyinka', 'Xuduudaha xogta', 'Maareynta fashilka']], ['03', 'Automation workflow', 'Ficilka xiga ee saxda ah fududee.', 'Waxaan isku xirnaa dhacdooyinka hawlgalka, habraacyada la ansixiyay, natiijooyinka AI ee ku salaysan xog, dib-u-eegista qofka, iyo ficillo la raadin karo.', ['Go’aanno AI lagu caawiyay', 'Xakameynta oggolaanshaha qofka', 'Fulinta ku habboon audit-ka', 'Waddooyin fallback gacanta ah']], ['04', 'Kaaliyeyaal hawleed dijitaal ah', 'Shaqada soo noqnoqota sii kaaliye la isku halayn karo.', 'Wakiil wuxuu naqshadayn karaa kaaliyeyaal xuduud leh oo loogu talagalay taageerada, dukumentiyada, maaliyadda, compliance-ka, iyo hawlaha. Caddeynta hadda la xaqiijiyay waxay weli tahay logistics.', ['Taageerada macaamiisha', 'Habaynta dukumentiyada', 'Is-dhiibista hawlaha', 'Hagaajin la maamulo']]], ctaTitle: 'Ku bilow hawsha qof walba og yahay inay dhib badan tahay.', ctaBody: 'Kulan hordhac ah wuxuu rabitaan AI oo ballaaran u beddelaa tallaabada koowaad ee cad oo la cabbiri karo.' },
  method: { ...en.method, eyebrow: 'Sida aan u shaqayno', title: 'Kalsoonida ku dhis isla nidaamka aad ku dhisayso software-ka.', intro: 'Hawl kasta waxay ka guurtaa faham una gudubtaa ficil la xakameeyay.', steps: [['01', 'Baadhis', 'Magacow dhibaatada hawlgalka, dadka ku lug leh, iyo natiijada ka dhigi lahayd shaqada mid qiimo leh.'], ['02', 'Khariidaynta hawlgalka', 'Raac nidaamyada, xogta, meelaha go’aanka, xaaladaha gaarka ah, fallback-yada gacanta, iyo masuuliyiinta tallaabo kasta.'], ['03', 'Dib-u-eegista amniga iyo gelitaanka', 'Qeex waxa automation-ku akhriyi karo, waxa uu qaban karo, cidda ansixin karta, iyo halka siruhu ku sugnaanayaan.'], ['04', 'Tijaabo la xakameeyay', 'Ku caddee hal hawl oo xuduud leh adigoo adeegsanaya xog staging ah, maarayn fashil oo cad, iyo cabbir bilow ah.'], ['05', 'Daahfurka production', 'Ku gudub sii-deyn qorshaysan oo leh rollback, masuul taageero, iyo xuduudo macaamiil oo cad.'], ['06', 'Kormeer iyo taageero', 'La soco natiijooyinka, jawaabaha provider-ka, khaladaadka, oggolaanshaha, iyo shaqada aan weli la dhammayn.'], ['07', 'Ballaadhin', 'Caddeynta hal hawl u isticmaal go’aaminta hawsha ku xigta ee mudan maalgashi.']], notesTitle: 'Waxa gaarsiin xirfad leh ka kooban tahay', notes: ['Masuul la magacaabay oo ficillada muhiimka ah leh', 'Tijaabo ka hor xog nool', 'Ogeysiis khalad iyo fallback gacanta ah', 'Diiwaan waxa dhacay iyo sababta', 'Waddo taageero kadib daahfurka'] },
  proof: { ...en.proof, eyebrow: 'Caddeyn si cad loo kala saaray', title: 'Hal dhacdo delivery ah, laga bilaabo signal ilaa caddeyn.', intro: 'Tani waa caddeyn hirgelin gudaha ah oo Wakiil iyo MK Deliver ah. Ma aha case study macaamiil dibadda ah.', caseTitle: 'Hawshu kuma eka qoraal AI ah.', caseBody: 'Delivery fashilmay wuxuu nidaamka ku galaa dhacdo joogto ah. Habraacu wuxuu hagaa qoraalka. Qof ayaa ansixiya ficilka muhiimka ah. Xaaladda ugu dambaysa ayaa mar kale la hubiyaa.', facts: [['06', 'workflow module oo la diiwaangeliyay'], ['01', 'xuduud oggolaansho qof'], ['00', 'farriin macaamiil oo tijaabada ku baxday']], evidence: ['Dhacdo joogto ah iyo outbox', 'Ilaalinta approval soo noqnoqda iyo revision duugoobay', 'Qoraal habraac ku salaysan oo English iyo Somali ah', 'Access controls iyo approval allowlists', 'Credential handling oo server-side ah', 'Tijaabooyin jiddo aan ammaan ahayn', 'Natiijada provider-ka dry-run iyo audit'], disclaimer: 'Caddeyntu waxay ka timid cloud dry-run gudaha ah. Farriimaha production wali way dansan yihiin demo-gan.' },
  security: { ...en.security, eyebrow: 'Amni iyo kalsooni', title: 'Automation-ku waa inuu masuuliyadda caddeeyaa, ma aha inuu qariyo.', intro: 'Waxaan naqshadeynaa xuduudda xakameynta ka hor qaybta caqliga leh.', controls: [['Oggolaanshaha qofka', 'Ficillada muhiimka ah ee macaamiisha waxay sugayaan qof la oggolaaday halkii ay ku socon lahaayeen talo aan dib loo eegin.'], ['Hubinta xaaladda cusub', 'Ficillada la ansixiyay waxay mar kale akhriyaan xaaladda hawlgalka ee ugu dambaysa ka hor fulinta.'], ['Xakameynta gelitaanka', 'Meelaha macaamiishu arkaan waxay helaan xog ammaan ah. Xogta hawlgalka gaarka ahi waxay ku jirtaa server-side access iyo approval allowlists.'], ['Diiwaan audit oo joogto ah', 'Dhacdooyinka, oggolaanshaha, isku dayada, jawaabaha provider-ka, iyo fashilladu waxay ahaanayaan kuwo la raadin karo.'], ['Maareynta fashilka', 'Shaqo soo noqnoqota, oggolaansho duugoobay, jawaab provider aan la hubin, iyo xog khaldan waxay leeyihiin waddooyin cad.'], ['Maareynta credentials', 'Credentials-ka server-side waxay ka fogaanayaan browser code iyo exports-ka dadweynaha.']], boundaryTitle: 'Demo ma aha production', boundaryBody: 'Showcase-ka dadweynuhu wuxuu sharxayaa qaabka hawlgalka. Demo-gu wuxuu adeegsadaa xog la xakameeyay iyo test recipient.', boundaryPoints: ['Xog macaamiil kuma jirto demo dadweynaha', 'Recipients production kuma jiraan adapter-ka hadda', 'Shahaado lama sheeganayo iyadoo aan si madax-bannaan loo xaqiijin'] },
  about: { ...en.about, eyebrow: 'Nagu saabsan', title: 'Shirkad u taagan shaqada u dhexeysa niyad iyo fulin.', intro: 'Wakiil wuxuu ka caawiyaa ganacsiyada inay aqoonta hawlgalka u beddelaan nidaamyo ogaan kara, go’aamin kara, ficil samayn kara, oo sharxi kara waxa dhacay.', statement: 'Ujeeddadu ma aha in AI lagu daro hawl. Ujeeddadu waa in hawsha laga dhigo mid ammaan badan, cad, oo fudud in la hagaajiyo.', pillars: [['Wax-ku-ool', 'Ku bilow shaqada maanta khilaafka abuureysa, ee ha ka bilaabin isbeddel aan la taaban karin.'], ['La xakameeyay', 'Dadka ku hay masuuliyadda go’aamada muhiimka ah, xuduuddana ka dhig mid muuqata.'], ['La ballaarin karo', 'Dhis aasaas ka kori kara hal workflow una gudbi kara lakab hawleed isku xiran.']], fitTitle: 'Ku habboon', fitBody: 'Kooxo leh shaqo soo noqnoqota, nidaamyo kala firdhisan, iyo hoggaamiye raba horumar la cabbiri karo.', notFitTitle: 'Ma aha jid gaaban', notFitBody: 'Wakiil ma ballanqaado sixir iskiis u shaqeeya ama beddelka masuuliyadda hawlgalka.' },
  contact: { ...en.contact, eyebrow: 'Bilow wada hadal', title: 'Noo keen hal hawl oo mudan in la hagaajiyo.', intro: 'Noo sheeg meesha shaqadu ku gaabiso iyo halka jid hawleed cad uu qiimo ka abuuri karo.', bookingTitle: 'Qabso kulan hordhac ah', bookingBody: 'Wadahadalka koowaad wuxuu fahmayaa hawsha, nidaamyada ku xeeran, iyo in tijaabo la xakameeyay ay macno samaynayso.', bookingButton: 'Fur jadwalka', emailLabel: 'Ama email', questionsTitle: 'Su’aalo lagu bilaabi karo', questions: ['Hawlee shaqo ayaa keenta isku-duwid laga hortagi karo?', 'Xaggee ayay shaqaaluhu macnaha ku lumiyaan nidaamyada dhexdiisa?', 'Ficilkee ayuu qof maanta go’aan ka gaaraa?', 'Maxay tijaabo guulaysatay caddayn lahayd?'], note: 'Qiimuhu wuxuu ku salaysan yahay scope-ka hawsha, complexity-ga nidaamka, khatarta, volume-ka, hirgelinta, iyo taageerada. Qiime sax ah waxaa la bixiyaa kadib discovery.' },
  demo: { ...en.demo, eyebrow: 'Sheeko hawleed la falgeli karo', title: 'Delivery fashilmay ilaa macaamil la xalliyay.', intro: 'Ciyaar sheekada si aad u aragto sida dhacdo hawleed uga gudubto intake, go’aan, approval, ficil, iyo audit.', play: 'Ciyaar sheekada oo dhan', reset: 'Dib u celi muuqaalka', ready: 'Diyaar', scenario: 'Scenario nool / MKD-0066', scenarioBody: 'Delivery lama guulaysan / macaamil lama helin', flow: ['Dhacdo la helay', 'Case la sameeyay', 'Qoraal AI', 'Approval qof', 'Action la audit gareeyay'], manualTitle: 'Automation la’aan', manualBody: 'Dadku waxay dhacdada ku maareeyaan channels kala firdhisan.', controlledTitle: 'Automation-ka Wakiil', controlledBody: 'Hal dhacdo waxay noqotaa hawl taageero oo la xakameeyay lana dib-u-eegi karo.', manual: ['Darawalku wuxuu soo sheegaa delivery fashilmay', 'Taageeradu waxay raadisaa shipment-ka', 'Qof ayaa go’aamiya waxa macaamilka loo sheego', 'Macaamilku wuxuu sugayaa jawaab', 'Diiwaanadu ma dhamaystirna'], controlled: ['Dhacdada delivery-ga waa la qabtaa', 'Case exception ah ayaa la sameeyaa', 'AI wuxuu diyaariyaa qoraal taageero oo xog ku salaysan', 'Oggolaanshaha qofka ayaa xakameeya ficilka', 'Ficilka iyo audit-ka waa la diiwaangeliyaa'], galleryTitle: 'Workflow modules. Hal sheeko hawleed.', galleryBody: 'Card kastaa wuxuu isku xirayaa module la diiwaangeliyay iyo ballanta ganacsi ee uu taageerayo.', miniFlow: ['Dhacdo', 'Hubi', 'Case', 'Hagid'], manualBadge: 'Gacan', controlledBadge: 'La xakameeyay', playWorkflow: 'Ciyaar workflow-ga', playing: 'Wuu socdaa', closingEyebrow: 'Wakiil AI Solutions', closingTitle: 'Ma aha chatbot kale. Waa lakab hawleed loogu talagalay shaqada muhiimka ah.', cards: [['Qabashada dhacdada', 'Qabso dhibaatada ka hor inta aysan lumin', 'Delivery fashilmay wuxuu noqdaa exception joogto ah oo la raadin karo.', 'Ogow'], ['Qabashada macaamiisha', 'Farriinta macaamilka u beddel ficil', 'Codsiga waa la hubiyaa, la fahmaa, lana marsiiyaa waddo ammaan ah.', 'Taageero'], ['Taageerada macaamiisha', 'Si ammaan ah uga jawaab, si caqli leh u gudbi', 'Su’aalaha ammaan ahi waxay helaan jawaab. Codsiyada muhiimka ahi waxay noqdaan handoff.', 'Taageero'], ['Xuduudda oggolaanshaha', 'Dadka ku hay xakameynta', 'AI wuxuu diyaariyaa talada. Qof la oggolaaday ayaa ansixiya ficilka.', 'Maamul'], ['Go’aan la ansixiyay', 'Ku shaqee xaqiiqooyinka ugu dambeeyay oo keliya', 'Shipment-ka mar kale ayaa la hubiyaa, jawaabta provider-kana waa la diiwaangeliyaa.', 'Fulin'], ['Dib-u-habaynta qoraalka', 'Jawaabta hagaaji adigoon xakameynta lumin', 'Qoraal la beddelay wuxuu ku soo noqdaa wareegga oggolaanshaha.', 'Hagaaji'], ['Canvas-ka showcase-ka', 'Qaabka hawlgalka ka dhig mid muuqda', 'Aragti diyaar u ah bandhiggu waxay isku xirtaa taageero, AI, xakameyn, ficil, iyo audit.', 'Sharax']] }
};

const copy = { en, so };

function useRoute() {
  const [route, setRoute] = useState(() => window.location.hash.replace(/^#\/?/, '') || 'home');
  useEffect(() => { const onHashChange = () => setRoute(window.location.hash.replace(/^#\/?/, '') || 'home'); window.addEventListener('hashchange', onHashChange); return () => window.removeEventListener('hashchange', onHashChange); }, []);
  return route;
}

function Link({ to = 'home', children, className = '', onClick }) { return <a className={className} href={`#/${to}`} onClick={onClick}>{children}</a>; }
function BrandMark() { return <span className="brand-mark" aria-hidden="true">W</span>; }
function Button({ to, href, children, variant = 'primary', onClick }) { const className = `button button-${variant}`; const content = <>{children}<span aria-hidden="true">↗</span></>; return to ? <Link to={to} className={className} onClick={onClick}>{content}</Link> : <a className={className} href={href} onClick={onClick}>{content}</a>; }

function Header({ lang, setLang, route, c }) {
  const [open, setOpen] = useState(false); const close = () => setOpen(false);
  const items = [['solutions', c.nav.solutions], ['method', c.nav.method], ['proof', c.nav.proof], ['security', c.nav.security], ['about', c.nav.about]];
  return <header className="site-header"><div className="container nav-wrap"><Link to="home" className="brand" onClick={close}><BrandMark /><span>WAKIIL</span></Link><nav className={`desktop-nav ${open ? 'nav-open' : ''}`} aria-label="Primary navigation">{items.map(([path, label]) => <Link key={path} to={path} className={route === path ? 'active' : ''} onClick={close}>{label}</Link>)}<Link to="demo" className="demo-link" onClick={close}>{c.nav.demo}</Link></nav><div className="nav-actions"><button className="language-switch" onClick={() => setLang(lang === 'en' ? 'so' : 'en')} aria-label={lang === 'en' ? 'Switch to Somali' : 'Switch to English'}><span className={lang === 'en' ? 'selected' : ''}>EN</span><span>/</span><span className={lang === 'so' ? 'selected' : ''}>SO</span></button><Button to="contact" variant="small">{c.nav.cta}</Button><button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation"><span /><span /></button></div></div></header>;
}

function SectionHeading({ eyebrow, title, body }) { return <div className="section-heading">{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2>{body && <p>{body}</p>}</div>; }
function Reveal({ children }) { return <div className="reveal">{children}</div>; }

function SignalCanvas({ c }) {
  return <div className="signal-canvas"><div className="canvas-top"><span className="live-label"><i /> {c.common.controlled}</span><span className="canvas-code">MKD-0066</span></div><div className="canvas-title">{c.demo.scenarioBody}</div><div className="canvas-line">{c.demo.flow.map((label, index) => <div className="canvas-node lit" key={label}><div className="node-dot">{String(index + 1).padStart(2, '0')}</div><span>{label}</span>{index < c.demo.flow.length - 1 && <b aria-hidden="true">→</b>}</div>)}</div><div className="canvas-readout"><span>{c.demo.captions[4]}</span><strong>{c.demo.flow[4]}</strong></div></div>;
}

function Footer({ c }) { return <footer className="site-footer"><div className="container footer-grid"><div><Link to="home" className="brand"><BrandMark /><span>WAKIIL</span></Link><p>{c.common.footerTagline}</p></div><div className="footer-links"><Link to="solutions">{c.nav.solutions}</Link><Link to="method">{c.nav.method}</Link><Link to="proof">{c.nav.proof}</Link><Link to="security">{c.nav.security}</Link><Link to="contact">{c.nav.cta}</Link></div><div className="footer-meta"><span>Wakiil AI Solutions</span><span>English / Somali</span><span>{c.common.footerClaims}</span></div></div></footer>; }
function CTA({ c, title, body }) { return <section className="cta-section container"><div className="cta-panel"><div><h2>{title}</h2><p>{body}</p></div><Button to="contact">{c.common.contact}</Button></div></section>; }

function Home({ c }) { return <main><section className="hero container"><div className="hero-copy"><div className="eyebrow">{c.home.eyebrow}</div><h1>{c.home.title}</h1><p className="hero-intro">{c.home.intro}</p><div className="hero-actions"><Button to="contact">{c.common.contact}</Button><Button to="demo" variant="ghost">{c.common.openDemo}</Button></div><p className="hero-note"><span className="note-rule" />{c.home.note}</p></div><div className="hero-visual"><SignalCanvas c={c} /><div className="visual-caption"><span>{c.home.eyebrow}</span><span>Wakiil control layer</span></div></div></section><section className="proof-strip"><div className="container proof-strip-inner"><span>{c.common.internal}</span><span>{c.common.controlled}</span><span>{c.common.capability}</span><Link to="security">{c.nav.security} ↗</Link></div></section><section className="section container"><SectionHeading eyebrow="" title={c.home.capabilitiesTitle} body={c.home.capabilitiesBody} /><div className="capability-grid">{c.home.capabilities.map(([label, title, body], index) => <Reveal key={label}><article className="capability"><div className="capability-index">0{index + 1}</div><div className="eyebrow">{label}</div><h3>{title}</h3><p>{body}</p><Link to="solutions" className="text-link">{c.common.explore} ↗</Link></article></Reveal>)}</div></section><section className="section proof-preview container"><div className="proof-preview-copy"><div className="eyebrow">{c.common.internal}</div><h2>{c.home.proofTitle}</h2><p>{c.home.proofBody}</p><Button to="proof" variant="ghost">{c.common.readProof}</Button></div><div className="fact-list">{c.home.proofFacts.map((fact, index) => <div key={fact}><span>0{index + 1}</span><strong>{fact}</strong></div>)}</div></section><section className="section method-preview"><div className="container"><SectionHeading eyebrow={c.nav.method} title={c.home.methodTitle} body={c.home.methodBody} /><div className="method-rail">{c.home.methodSteps.map((step, index) => <div className="method-node" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < c.home.methodSteps.length - 1 && <i />}</div>)}</div><div className="center-link"><Button to="method" variant="ghost">{c.nav.method}</Button></div></div></section><CTA c={c} title={c.home.bottomTitle} body={c.home.bottomBody} /></main>; }

function Solutions({ c }) { return <main className="inner-page"><section className="page-hero container"><SectionHeading eyebrow={c.solutions.eyebrow} title={c.solutions.title} body={c.solutions.intro} /></section><section className="container solution-list">{c.solutions.items.map(([number, label, title, body, points]) => <Reveal key={number}><article className="solution-row"><div className="solution-number">{number}</div><div className="solution-main"><div className="eyebrow">{label}</div><h2>{title}</h2><p>{body}</p></div><ul>{points.map(point => <li key={point}><span>+</span>{point}</li>)}</ul></article></Reveal>)}</section><CTA c={c} title={c.solutions.ctaTitle} body={c.solutions.ctaBody} /></main>; }
function Method({ c }) { return <main className="inner-page"><section className="page-hero container"><SectionHeading eyebrow={c.method.eyebrow} title={c.method.title} body={c.method.intro} /></section><section className="container method-layout"><div className="process-list">{c.method.steps.map(([number, title, body]) => <article className="process-step" key={number}><span className="process-number">{number}</span><div><h2>{title}</h2><p>{body}</p></div></article>)}</div><aside className="notes-panel"><div className="eyebrow">{c.method.notesTitle}</div><ul>{c.method.notes.map(note => <li key={note}><span>+</span>{note}</li>)}</ul></aside></section><CTA c={c} title={c.home.bottomTitle} body={c.home.bottomBody} /></main>; }
function Proof({ c }) { return <main className="inner-page"><section className="page-hero container"><SectionHeading eyebrow={c.proof.eyebrow} title={c.proof.title} body={c.proof.intro} /></section><section className="container claim-legend"><span><b>{c.common.internal}</b></span><span><b>{c.common.capability}</b></span><span><b>{c.common.planned}</b></span><span><b>{c.common.customerResult}</b> {c.common.claimSuffix}</span></section><section className="container case-study"><div className="case-copy"><div className="eyebrow">{c.proof.caseLabel}</div><h2>{c.proof.caseTitle}</h2><p>{c.proof.caseBody}</p><Link to="demo" className="text-link">{c.common.openDemo} ↗</Link></div><SignalCanvas c={c} /></section><section className="container fact-grid">{c.proof.facts.map(([value, label]) => <div className="fact-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</section><section className="container evidence-layout"><div><SectionHeading title={c.proof.evidenceTitle} /><p className="disclaimer">{c.proof.disclaimer}</p></div><div className="evidence-list">{c.proof.evidence.map((item, index) => <div key={item}><span>0{index + 1}</span><strong>{item}</strong></div>)}</div></section><CTA c={c} title={c.home.bottomTitle} body={c.home.bottomBody} /></main>; }
function Security({ c }) { return <main className="inner-page"><section className="page-hero container"><SectionHeading eyebrow={c.security.eyebrow} title={c.security.title} body={c.security.intro} /></section><section className="container security-grid">{c.security.controls.map(([title, body], index) => <Reveal key={title}><article className="security-card"><span>0{index + 1}</span><h2>{title}</h2><p>{body}</p></article></Reveal>)}</section><section className="container boundary"><div className="boundary-copy"><div className="eyebrow">{c.common.controlled}</div><h2>{c.security.boundaryTitle}</h2><p>{c.security.boundaryBody}</p></div><ul>{c.security.boundaryPoints.map(point => <li key={point}><span>+</span>{point}</li>)}</ul></section><CTA c={c} title={c.home.bottomTitle} body={c.home.bottomBody} /></main>; }
function About({ c }) { return <main className="inner-page"><section className="page-hero container about-hero"><SectionHeading eyebrow={c.about.eyebrow} title={c.about.title} body={c.about.intro} /><div className="about-statement">{c.about.statement}</div></section><section className="container pillars">{c.about.pillars.map(([title, body], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{body}</p></article>)}</section><section className="container fit-grid"><div><div className="eyebrow">{c.about.fitTitle}</div><h2>{c.about.fitBody}</h2></div><div><div className="eyebrow">{c.about.notFitTitle}</div><h2>{c.about.notFitBody}</h2></div></section><CTA c={c} title={c.home.bottomTitle} body={c.home.bottomBody} /></main>; }
function Contact({ c }) { const bookingHref = siteConfig.bookingUrl || `mailto:${siteConfig.contactEmail}?subject=Wakiil%20discovery%20call`; return <main className="inner-page"><section className="page-hero container"><SectionHeading eyebrow={c.contact.eyebrow} title={c.contact.title} body={c.contact.intro} /></section><section className="container contact-layout"><div className="booking-panel"><div className="eyebrow">{c.contact.bookingTitle}</div><h2>{c.contact.bookingBody}</h2><a className="button button-primary" href={bookingHref}>{c.contact.bookingButton} ↗</a><div className="email-link"><span>{c.contact.emailLabel}</span><a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a></div></div><div className="question-panel"><h2>{c.contact.questionsTitle}</h2><ul>{c.contact.questions.map((question, index) => <li key={question}><span>0{index + 1}</span>{question}</li>)}</ul><p className="contact-note">{c.contact.note}</p></div></section></main>; }

function Replay({ c }) {
  const [active, setActive] = useState(-1); const [playing, setPlaying] = useState(false);
  useEffect(() => { if (!playing) return undefined; const timer = window.setInterval(() => setActive(current => { if (current >= c.demo.flow.length - 1) { setPlaying(false); return current; } return current + 1; }), 1150); return () => window.clearInterval(timer); }, [playing, c.demo.flow.length]);
  return <section className="replay-panel"><div className="replay-header"><div><div className="eyebrow">{c.demo.scenario}</div><p>{c.demo.scenarioBody}</p></div><span className="replay-state">{active >= 0 ? c.demo.flow[active] : c.demo.ready}</span></div><div className="replay-flow">{c.demo.flow.map((step, index) => <div className={`replay-step ${active >= index ? 'active' : ''} ${active === index ? 'current' : ''}`} key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < c.demo.flow.length - 1 && <i />}</div>)}</div><p className="replay-caption">{active >= 0 ? c.demo.captions[active] : c.demo.intro}</p><div className="replay-actions"><button className="button button-primary" onClick={() => { setActive(0); setPlaying(true); }}>{c.demo.play} ▶</button><button className="button button-ghost" onClick={() => { setActive(-1); setPlaying(false); }}>{c.demo.reset}</button></div></section>;
}
function Demo({ c }) { const [active, setActive] = useState(null); return <main className="inner-page demo-page"><section className="page-hero container"><SectionHeading eyebrow={c.demo.eyebrow} title={c.demo.title} body={c.demo.intro} /></section><div className="container"><Replay c={c} /></div><section className="container compare-grid"><article><div className="compare-header"><div><h2>{c.demo.manualTitle}</h2><p>{c.demo.manualBody}</p></div><span className="badge badge-muted">{c.demo.manualBadge}</span></div><ol>{c.demo.manual.map((step, index) => <li key={step}><span>{index + 1}</span>{step}</li>)}</ol></article><article className="controlled-compare"><div className="compare-header"><div><h2>{c.demo.controlledTitle}</h2><p>{c.demo.controlledBody}</p></div><span className="badge badge-accent">{c.demo.controlledBadge}</span></div><ol>{c.demo.controlled.map((step, index) => <li className={active === index ? 'active' : ''} key={step}><span>{index + 1}</span>{step}</li>)}</ol></article></section><section className="container gallery-section"><SectionHeading title={c.demo.galleryTitle} body={c.demo.galleryBody} /><div className="workflow-grid">{c.demo.cards.map((card, index) => <article className={`workflow-card ${active === index ? 'is-active' : ''}`} key={card[0]}><div className="workflow-head"><div><span>{String(index + 1).padStart(2, '0')} / {card[0]}</span><h2>{card[1]}</h2></div><b>{card[3]}</b></div><p>{card[2]}</p><div className="mini-flow">{c.demo.miniFlow.map((step, stepIndex) => <span className={active === index && stepIndex <= 2 ? 'active' : ''} key={step}><i>{stepIndex + 1}</i>{step}</span>)}</div><button className="card-play" onClick={() => setActive(index)}>{active === index ? c.demo.playing : c.demo.playWorkflow} ↗</button></article>)}</div></section><section className="container demo-close"><div><div className="eyebrow">{c.demo.closingEyebrow}</div><h2>{c.demo.closingTitle}</h2></div><Button to="contact">{c.common.contact}</Button></section></main>; }

function App() {
  const route = useRoute(); const [lang, setLang] = useState(() => window.localStorage.getItem('wakiil-language') || 'en');
  useEffect(() => { window.localStorage.setItem('wakiil-language', lang); }, [lang]);
  useEffect(() => { document.documentElement.lang = lang === 'so' ? 'so' : 'en'; }, [lang]);
  useEffect(() => { window.scrollTo(0, 0); }, [route]);
  const c = useMemo(() => copy[lang] || copy.en, [lang]);
  const page = route === 'solutions' ? <Solutions c={c} /> : route === 'method' ? <Method c={c} /> : route === 'proof' ? <Proof c={c} /> : route === 'security' ? <Security c={c} /> : route === 'about' ? <About c={c} /> : route === 'contact' ? <Contact c={c} /> : route === 'demo' ? <Demo c={c} /> : <Home c={c} />;
  return <div className="app-shell"><Header lang={lang} setLang={setLang} route={route} c={c} />{page}<Footer c={c} /></div>;
}

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
